config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'}do
    namespace :v1 do
      get 'news', to: 'tweets#news'
      get 'date/:date_init/:date_end', to: 'tweets#date', as: 'date'
      get 'create', to: 'tweets#create'
    end
  end
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tweets
  # resources :likes
  devise_for :users
  root to: "tweets#index"
  post 'tweets/retweet/:id', to: 'tweets#retweet', as: 'retweet'
  post 'tweets/:tweet_id/likes', to: 'likes#like', as: 'like'
  delete 'likes/:id', to: 'likes#dislike', as: 'dislike'
  post 'follows/:id', to: 'follows#follow', as: 'follow'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :content, presence: true
    scope :tweets_for_me, -> (user) {where(:user_id => user.followeds.pluck(:followed_id))}
    belongs_to :user
    has_many :retweets, class_name: 'Tweet', foreign_key: 'tweet_id', dependent: :destroy
    belongs_to :original_tweet, class_name: 'Tweet', foreign_key: 'tweet_id', optional: true
    has_many :likes, dependent: :destroy
end

app/controllers/api/v1/tweets_controller.rb
class Api::V1::TweetsController < ApplicationController
  include ActionController::HttpAuthentication::Basic::ControllerMethods
  #autenticacion para poder accceder a api
    http_basic_authenticate_with name: "hello", password: "123123"

    #visualizacion api
    def news 
        tweets = Tweet.all.order(created_at: :desc).limit(50)
        @tweets = tweets.map {|tweet| { 
            id: tweet.id, 
            content: tweet.content, 
            user: tweet.user_id,
            like_count: tweet.likes.count,
            retweets: tweet.tweet_id, 
            retwitter_from: tweet.user_id
            }}
        render json: @tweets
    end

#busqueda segun fechas date_init y date_end
    def date
        @tweets = Tweet.where('created_at BETWEEN ? AND ?', params[:date_init], params[:date_end])
        @api_date = []
        @tweets.each do |tweet|
        @api_date << { 
            id: tweet.id, 
            content: tweet.content, 
            user: tweet.user_id,
            like_count: tweet.likes.count,
            retweets: tweet.tweet_id, 
            retwitter_from: tweet.user_id
            }
        end
        render json: @tweets
    end
    #creacion de tweet usuario
    def create
        @tweet =  User.first.tweets.create(content: params[:content])
    
        if @tweet.save
            render json: @tweet, status: :created
        else
            render json: @tweet.errors, status: :unprocessable_entity
        end
    end

    def update
        if @tweet.update(tweet_params)
            render json: @tweet, status: :ok
        else
            render json: @tweet.errors, status: :unprocessable_entity
        end
    end
    def destroy
        @tweet.destroy
        head :no_content
    end
    private

    def set_new
        @tweet = Tweet.find(params[:id])
    end
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy :retweet]


  def index
    # @user_likes = Like.where(user: current_user).pluck(:tweet_id)
  # Buqueda parcial
  if params[:q]
    @tweets = Tweet.where('content LIKE ?', "%#{params[:q]}%").order(created_at: :desc).page params[:page]
  elsif user_signed_in?
    @tweets = Tweet.tweets_for_me(current_user).order(created_at: :desc).page params[:page]
    
  else
    @tweets= Tweet.eager_load(:user, :likes).order(created_at: :desc).page params[:page]
    
  end
    @tweet = Tweet.new
    @user_likes = Like.where(user: current_user).pluck(:tweet_id)
    # @user_likes = Like.eager_load(:user, :tweet).where(user: current_user).pluck(:tweet_id)
    # @users = User.where.not(id: current_user.id) if user_signed_in?
    # @users = User.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show
    # @tweet = Tweet.find(params[:id])
    # @post_likes = @post.likes
  end

  # GET /tweets/new -- si el usuario esta logeado, que se cree el tweet, de lo contrario se redirige al iniciar secion
  def new 
    if user_signed_in?
      @tweet = Tweet.new
    else
      redirect_to new_user_session_path
    end 
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(content: params[:tweet][:content])
    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { redirect_to root_path, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def retweet
    @tweet = Tweet.find(params[:id])
    new_tweet = Tweet.create(content: @tweet.content, user: current_user)
    @tweet.retweets << new_tweet
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :retweet)
    end
end

app/helpers/api/v1/tweets_helper.rb
module Api::V1::TweetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

    def hashtag(content)
        format_content = content.split(" ")
        tag =[]
        format_content.each do |p|
            if p.start_with?("#")
                p = link_to p, controller: 'tweets', q: p
            end
            tag.push(p)
        end
        raw tag.join(" ")
    end
end

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, local: true) do |f| %>
  <% if @tweet.errors.any? %>
    <div id = 'error_explanation'>
      <h2>Este tweet no se pudo crear por las siguientes razones</h2>
      <ul>
        <% tweet.errors.full_messages.each do |msg|%>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <div class="card text-center mx-auto col-md-6 mb-3">
      <h3 class="card-title py-3">¿Qué está pasando?</h3>
      <div class="form-group">
        <%= f.text_area :content, row: 3, class: 'col-md-7'%>
      </div>
      <div class = 'actions' my-2>
        <%= f.submit class: 'btn btn-primary'%>
      </div>
    </div>
  <% end %>
<% end %>

app/views/tweets/_users_follow.html.erb
<div class="card-body" aling="left"> 
    <div class="d-flex align-items-center"> 
        <% current_user.can_follow.each do |user| %>
            <% if current_user.id != user.id %>
                <%= link_to follow_path(user.id), method: :post do%>
                    <div class="card text-white bg-primary rounded-3 border" style="max-width: 60px;">
                        <%= image_tag user.user_photo, width:"100%" %>
                    </div>
                <% end %>  
            <% end %>
        <% end %>
    </div>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<% if user_signed_in? %>
    <%= render 'users_follow' %>
<% end %>

  <%= render 'form', tweet: @tweet %>
  
  <% @tweets.each do |tweet| %>
    <div class="card"> 
        
      <div class="card-header" aling="left"> <!-- mostrar imagen y nombre en los tweets alineados a la izquierda-->
        <div class="d-flex align-items-center">
          <div class="card text-white bg-primary rounded-3 border" style="max-width: 60px;">
            <%= image_tag tweet.user.user_photo%>
          </div>
          <b >@<%= tweet.user.user_name %></b>
        </div>
      </div>
      <div class="card-body">
        <p class="card-text">
          <%= hashtag(tweet.content) %>
        </p>
        <div class="text-muted h7 mb-2"><%= link_to time_ago_in_words(tweet.created_at), tweet_path(tweet), style:'text-decoration: none' %>
        </div>
      </div>

      <div class="card-footer">
        <% if @user_likes.include?(tweet.id) %>  
        
          <%= link_to dislike_path(tweet.id), method: :delete do%>
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart-broken" width="28" height="28" viewBox="0 0 24 24" stroke-width="2" stroke="#ff2825" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
              <path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
              <path d="M12 7l-2 4l4 3l-2 4v3" />
            </svg>
          <% end %>
        <% else %>
          <%= link_to like_path(tweet.id), method: :post do%>
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart" width="28"   height="28" viewBox="0 0 24 24" stroke-width="2" stroke="#ff2825" fill="none" stroke-linecap="round"  stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
              <path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428m0 0a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
            </svg>
          <% end %>
        <% end %> 
        <%= tweet.likes.count %>
          <!--retweet button-->
          <%= link_to retweet_path(tweet.id), method: :post do%>
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-recycle" width="28" height="28" viewBox="0 0 24 24" stroke-width="2" stroke="#9e9e9e" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
              <path d="M12 17l-2 2l2 2m-2 -2h9a2 2 0 0 0 1.75 -2.75l-.55 -1" />
              <path d="M12 17l-2 2l2 2m-2 -2h9a2 2 0 0 0 1.75 -2.75l-.55 -1" transform="rotate(120 12 13)" />
              <path d="M12 17l-2 2l2 2m-2 -2h9a2 2 0 0 0 1.75 -2.75l-.55 -1" transform="rotate(240 12 13)" />
            </svg>
              <span><%= tweet.retweets.count %></span>
          <% end %>
      </div>
    </div>
  <% end %>


  <%= paginate @tweets %>


<div class="actions">
  <%= link_to_previous_page  @tweets, 'Página anterior' %>
  <%= link_to_next_page @tweets, 'Página siguiente'%>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Photo</strong>
  <img src="<%= @tweet.user.user_photo %>" width="60" height="60">
</p>

<p>
  <strong>Name</strong>
  <%= @tweet.user.user_name %>
</p>

<p>
  <strong>Content</strong>
  <%= @tweet.content %>
</p>

<div class="container">
    <!-- iteramos los likes para traer los id de usuario y luego su foto -->
    <p><%= @tweet.likes.count %> <%= (@tweet.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <div>
      <% Like.where(tweet_id: @tweet.id).each do |photo| %>
        <% user_photo =  photo.user_id %>
          <div class="d-inline-block p-2">
            <img src="<%= User.find(user_photo).user_photo%>" width="60" height="60">
            <p><%= User.find(user_photo).user_name %></p>
          </div>
      <% end %>
    </div>
  </div>



<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>